# -*- coding: utf-8 -*-
"""Oobevaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xd1u9VPp8VG7rIV7VSMLEkSzUeq8BmE1
"""

#oob evaluation for random forest

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

df = pd.read_csv('heart.csv')

X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

rf = RandomForestClassifier(oob_score=True)
rf.fit(X_train,y_train)
RandomForestClassifier(oob_score=True)

rf.oob_score_

y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)