# -*- coding: utf-8 -*-
"""Decisiontrees1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQRI23mFK-sKJSp5Sqd596js85XOpKhc
"""

from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y, test_size = 0.2)

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

from sklearn.tree import plot_tree
plot_tree(clf)